#!/usr/bin/env bash
set -eo pipefail
if [[ -n $OMNIA_DEBUG ]]; then set -x; fi

cd "$(cd "${0%/*/*}" && pwd)/lib"
. ./log.sh

if _goferData="$(gofer price --config "$GOFER_CONFIG" --format ndjson "$1")"
then
	jq -c '{
  	asset: (.base+"/"+.quote),
  	median: .price,
  	sources: (
  		[ ..
  		| select(type == "object" and .type == "origin" and .error == null)
  		| {(.base+"/"+.quote+"@"+.params.origin): (.price|tostring)}
  		]
  		| add
  	)
  }' <<<"$_goferData"
else
	error "could not get price" "$(jq -r '.error' <<<"$_goferData")" "asset=$1"
	exit 1
fi
