name: Push Docker DEV Image
on:
  workflow_dispatch: # Allow manual trigger
  workflow_run:
    workflows: ["Omnia Tests"] # Depend on success from tests
    types: [completed]
    branches: 
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'develop'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
#
      # - name: Build and Publish Deployer Image to Github Packages
      #   if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only if tests passed
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     file: ./docker/deployer/Dockerfile
      #     platforms: linux/amd64,linux/arm64
      #     push: ${{ github.event_name != 'pull_request' }} # Build only on push to master
      #     tags: ghcr.io/chronicleprotocol/deployer:latest,ghcr.io/chronicleprotocol/deployer:dev
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      - name: Build and Publish Omnia DEV Image to Github Packages
        if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'}} # Only if tests passed or triggered manually
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./omnia/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }} # Build only on push to master
          tags: ghcr.io/chronicleprotocol/omnia_feed:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
